name: Release to Cocoapods

on:
  push:
    branches:
    - master
    - release/*
    - hotfix/*

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Trunk info
          # pod trunk register developer@mozocoin.io 'Mozo Developer' --description='GitHub Actions Token'
          # grep -A2 'trunk.cocoapods.org' ~/.netrc
        run: |
          pod trunk me

      - name: Deploy to Cocoapods
        run: |
          pod repo update
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          # Get your trunk token by using: pod trunk me --verbose